### ISSUE TITLE
Awsomeness with schematics, one side effect I did not expect, water above the shorline..

### ISSUE THREAD

**Issue by directgumby** [mathuin/TopoMC#38] opened 2013-08-26 18:40 UTC
Hello,

I got a great map created late last night of a section around the Flathead Lake that includes Wild Horse Island.  I turned on the use schematics and it did a fair job of creating villages.  The only issue I noticed was that sometimes the village schematics ended up on the shoreline - when this happened what I saw as the house area running under the water.  The water would be sanding one block higher that the rest of the land around it.

I am wondering if this is due to:
1) The use of schematics 
2) The use of the --sealevel 32 --maxdepth 16

Is there something I can send you so that you can take a look?
Note: I am going to setup another rendering tonight without the use of the schematics to see if that helps with the problem.

On a more interesting note:  It was very cool to see that section rendered at a scale of 4 --- it ends up being a very large map to say the least... but the app does a really great job of laying out the land structure, populating trees and ore... I think it planted near 300,000 tress and near 700,000 bits of ore... darn cool to see it all working!

Brett

**Comment by mathuin** [comment] 2013-08-26 20:13
Wow!  That sounds pretty awesome!

http://www.minecraftwiki.net/wiki/Programs_and_editors/Mapping shows tons of mappers that work on Windows.  I only have experience with c10t and minutor myself, but you may find mapcrafter or mcmap more to your liking.

I am interested in exactly which part of the lake and/or island has the water/sand issue.  It is rare but sometimes due to rounding there are occasional water blocks that are where they shouldn't, but it should be on the order of one in a thousand to one in ten thousand.  Let me know the real-world coordinates of that area and I'll build it at home.

Thanks again!  Can't wait to see the map!

Jack.

**Comment by directgumby** [comment] 2013-08-27 03:59
Hey Jack,

I tried sending a mail with attachments and it got bounced back - do you have an email I can send this to you directly?

Thanks,
Brett

Sent from my Windows Phone

**Comment by mathuin** [comment] 2013-08-27 05:26
Sure, it's mathuin@gmail.com -- thanks!

Jack.

**Comment by mathuin** [comment] 2013-08-27 20:53
Okay, I rendered a map but it's way bigger than will fit on the issue tracker. :-)

One thing that's not coming through on your email is the coordinates of the problem regions.  I should have some time in the next few days to cruise through and search for a few.

The fragmented house thing is due to the fact that the residential area goes right up to the water's edge, and the residential template is pretty simple.  In a future release, I'm hoping to generate villages the way Minecraft does but I haven't had the time to figure it out yet.  For now, the schematics give a good impression of the various types of civilization.  They are biased towards flatness and deal poorly with arbitrary hills, though. :-(

Jack.

**Comment by directgumby** [comment] 2013-08-28 23:41
Hey Jack,

I wanted to check back with you to see if you got the email with all of the data.

If not, please let me know and I’ll send it to you again.

If so, please let me know if you need any more information from me on the areas I highlighted for you.

Thanks,
Brett

Sent from Windows Mail

From: Brett Humphrey
Sent: ‎Monday‎, ‎August‎ ‎26‎, ‎2013 ‎8‎:‎59‎ ‎PM
To: mathuin/TopoMC, mathuin/TopoMC

Hey Jack,

I tried sending a mail with attachments and it got bounced back - do you have an email I can send this to you directly?

Thanks,
Brett

Sent from my Windows Phone

**Comment by mathuin** [comment] 2013-08-29 00:01
I did get your message, and built the world.  With OpenCL it didn't take very long at all and there wasn't much of a memory problem -- I have 16G RAM and 16G swap and I don't think it even hit swap.  I used the buildmaps tool to build some maps but I haven't yet identified the exact locations where the water goes high.  I have copied it to my single-player saves directory so I can look sometime tonight or tomorrow.  If you know the XYZ coordinates for the specific points you'd like me to visit, post them here?

Jack.

**Comment by mathuin** [comment] 2013-08-29 01:38
Okay, I was able to identify one particular location where the water was one block higher than the land.  It was in the vicinity of X=-342497 Z=723655.

I'm going to rebuild the world without schematics to see if that fixes things.  If not, then I'll try some of the other settings.

Jack.

**Comment by mathuin** [comment] 2013-08-29 14:53
Okay, I rebuilt it without schematics and the problem is still there, though lesser.

The reason the problem occurs is due to the fact that the landcover files (the ones used to determine where water goes) are projected and interpolated a little differently than the elevation files (the ones used to determine how high things are).  In this case, the elevation smoothing appears to have increased the apparent elevation of six or eight water blocks, which causes a little mound of water.

The schematics seem to make the problem worse, but at this point I'm not sure exactly why.

It would be a big, big, big help if you could use your knowledge of the local area to narrow down the exact latlong of the point I found on your map.  Then I can render it in a minute instead of an hour, and I can show up right on the site instead of flying for a mile or two. :-)

Thanks!

**Comment by directgumby** [comment] 2013-08-29 17:10
Hey Jack,

I'msorry for the long delay, for some reason these were going to the junk folder - I'll try to get you this data in the next day or two as I have a number of things going on today and tomorrow.

Thanks,

Brett

Sent from Windows Mail

From: Jack Twilley
Sent: ‎Thursday‎, ‎August‎ ‎29‎, ‎2013 ‎7‎:‎53‎ ‎AM
To: mathuin/TopoMC
Cc: directgumby

Okay, I rebuilt it without schematics and the problem is still there, though lesser.

The reason the problem occurs is due to the fact that the landcover files (the ones used to determine where water goes) are projected and interpolated a little differently than the elevation files (the ones used to determine how high things are). In this case, the elevation smoothing appears to have increased the apparent elevation of six or eight water blocks, which causes a little mound of water.

The schematics seem to make the problem worse, but at this point I'm not sure exactly why.

It would be a big, big, big help if you could use your knowledge of the local area to narrow down the exact latlong of the point I found on your map. Then I can render it in a minute instead of an hour, and I can show up right on the site instead of flying for a mile or two. :-)

Thanks!

**Comment by directgumby** [comment] 2013-08-31 03:19
Hey Jack,

Here is some more info for you (and a smaller section to look at).

47.853569, -114.277617 to 47.846571, -114.267253 should work.

See the attached pictures, this should help you get closer as well.

The interesting thing about the 3D images that there are two things going on there:
You can see the water is above the shore 
You can see where the water is stacked on top of the water that is above the shore.

I hope this helps and please let me know if you need more locations.

It seems to happen across a great number of areas on this map.

Thank you for your time, help, and for looking into this more closely.

Brett

Sent from Windows Mail

From: Jack Twilley
Sent: ‎Thursday‎, ‎August‎ ‎29‎, ‎2013 ‎7‎:‎53‎ ‎AM
To: mathuin/TopoMC
Cc: directgumby

Okay, I rebuilt it without schematics and the problem is still there, though lesser.

The reason the problem occurs is due to the fact that the landcover files (the ones used to determine where water goes) are projected and interpolated a little differently than the elevation files (the ones used to determine how high things are). In this case, the elevation smoothing appears to have increased the apparent elevation of six or eight water blocks, which causes a little mound of water.

The schematics seem to make the problem worse, but at this point I'm not sure exactly why.

It would be a big, big, big help if you could use your knowledge of the local area to narrow down the exact latlong of the point I found on your map. Then I can render it in a minute instead of an hour, and I can show up right on the site instead of flying for a mile or two. :-)

Thanks!

**Comment by mathuin** [comment] 2013-08-31 18:37
I built the region at your coordinates at the highest possible zoom (one to one) and saw something pretty bizarre:

![2013-08-31_11 22 44](https://f.cloud.github.com/assets/221823/1062753/0dc8766a-126b-11e3-818a-b677ec439644.png)

There is something wrong with the elevation values over the water.  Or, an invisible giant is walking across the lake surface. :-)

When I looked underwater, the "footprints" continue to the sea floor:

![2013-08-31_11 25 28](https://f.cloud.github.com/assets/221823/1062754/336c8d84-126b-11e3-8c3a-eb8263b54db4.png)

Normal behavior for USGS data is for the elevation to stay the same across bodies of water.  For whatever reason, that is not consistent in your neck of the woods.  I wish I had support for the higher-resolution data, but they changed how it was handled and I haven't had time to fix it.  Unfortunately, even if I had support for the higher-resolution data, they haven't yet imaged this area. :-(

Jack.

**Comment by directgumby** [comment] 2013-09-02 15:24
Hey Jack,

Thank you for looking into this.  It sounds like the short answer is that I will have to do some shoreline work with a map editor to get it all looking good.

Or, I can just leave it and make it "part of the world" for now.

A question for you, what mapper program are you using in these screen shots?

Thanks,
Brett

Sent from my Windows Phone

**Comment by mathuin** [comment] 2013-09-02 15:30
Those images were screenshots.  I use Rei's Minimap and Optifine as mods via Magic Launcher and it works pretty well!

Jack.

**Comment by mathuin** [comment] 2014-03-02 02:10
This particular issue was identified as a problem with the USGS data and not my app, so I'm going to close it.

**Closed as completed by mathuin** 2014-03-02 02:10 UTC
