### ISSUE TITLE
Failure in GetDataset.py (main->extractFiles->getmember-> file not found)

### ISSUE THREAD

**Issue by pm2845** [mathuin/TopoMC#7] opened 2012-02-14 08:24 UTC
Hi! Cool program!

I was trying to do the demo from the website on New York City, but I ran into the following problem:

Command was "python GetDataset.py --region NewYorkCity --ymax 40.771 --ymin 40.683 --xmin -74.0490 --xmax -73.9610"

Results were:
P:\Minecraft\TopoMC>python GetDataset.py --region NewYorkCity --ymax 40.771 --ym
in 40.683 --xmin -74.0490 --xmax -73.9610
ERROR 4: `Datasets\NewYorkCity\L0102HT\L0102HT.tif' does not exist in the file s
ystem,
and is not recognised as a supported dataset name.

ERROR:dataset:NewYorkCity: lc dataset didn't open
Retrieving new dataset NewYorkCity...
Checking inventory service for coverage.
Inventory service has the following product IDs: L01,ND9
Configured the following layer IDs: L0102HT,ND902HT
Requested URLs for layer ID L0102HT...
Requested URLs for layer ID ND902HT...
Received download URLs, downloading now!
  Requesting download.
  request ID is 20120214.020743712.075158140096
  status is Extracting Data
  status is Extracting Data
  status is Extracting Metadata
  status is Extracting Metadata
  status is
  status is Retrieving Remote Archive File
  downloading 50062529.tgz now!
  Requesting download.
  request ID is 20120214.021015961.075158140096
  status is Extracting Data
  status is Retrieving Remote Archive File
  downloading 13173707.tgz now!
Traceback (most recent call last):
  File "GetDataset.py", line 504, in <module>
    sys.exit(main(sys.argv))
  File "GetDataset.py", line 498, in main
    extractFiles(datasetDir)
  File "GetDataset.py", line 394, in extractFiles
    cFile.extract(compimage, layersubdir)
  File "C:\Python27\lib\tarfile.py", line 2074, in extract
    tarinfo = self.getmember(member)
  File "C:\Python27\lib\tarfile.py", line 1794, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename '13173707\\13173707.tif' not found"

Thanks for your help!

**Comment by mathuin** [comment] 2012-02-14 15:39
I don't have a Windows system for development purposes, so it's a bit more challenging to get things to work.  You may have better luck using ZIP format instead of TGZ for the downloaded files.

As you may have noticed, I'm in the middle of a rewrite.  The rewrite shouldn't affect the TGZ/ZIP situation, but it will result in better quality output.  I will notify you when it is ready for general testing, but if you want to explore the bleeding edge, it's the git branch "features/regions".

Jack.

**Comment by pm2845** [comment] 2012-02-14 16:51
Hi! Thanks for getting back so quickly!

If this is some kind of windows bug, I'm happy to try this on Linux. I'll
let you know the results (when I get around to this!)
On Feb 14, 2012 8:39 AM, "Jack Twilley" <
reply@reply.github.com>
wrote:

**Comment by mathuin** [comment] 2012-02-14 18:30
Yes, it's a Windows issue related to pathname handling.  Give it a try in Linux, see how it goes!

Jack.

**Comment by pm2845** [comment] 2012-02-15 10:15
Still haven't gotten a chance to try this on linux yet, but I tried to use
your NewYorkCity map from the website in the meanwhile. It seems like
Minecraft would just regenerate the terrain over it instead of actually
loading the terrain though?

On Tue, Feb 14, 2012 at 11:30 AM, Jack Twilley <
reply@reply.github.com

**Comment by mathuin** [comment] 2012-02-16 02:05
That's not what should happen.  Minecraft will generate terrain around the edges of the downloaded map, but not over it.  Can you tell me more about what happens when you try to use it?

Jack.

**Comment by pm2845** [comment] 2012-02-23 02:31
Hi Jack,

Sorry it took a while to get back to you; I just tried this on Linux, and
this was what I got:
ERROR:dataset:NewYorkCity: elevation image not found
Retrieving new dataset NewYorkCity...
Checking inventory service for coverage.
Inventory service has the following product IDs: L01,ND9
Configured the following layer IDs: L0102HT,ND902HT
Requested URLs for layer ID L0102HT...
Requested URLs for layer ID ND902HT...
Received download URLs, downloading now!
  Requesting download.
The server couldn't fulfill the request.
Error code:  503
Download failed for layer ID ND902HT!

Seems like the geoloc servers are down?

(Same python command as on windows, for the record)

On Wed, Feb 15, 2012 at 7:05 PM, Jack Twilley <
reply@reply.github.com

**Comment by mathuin** [comment] 2012-02-23 03:37
Yes.  When you see 503, that means "service unavailable".  The USGS servers have been really spotty lately, which is frustrating because I'm trying to rebuild my showcase maps and worlds for the website. :-)

I have pushed out some changes tonight which disable structures by default and which use OpenCL if it's present on your system.  I have also updated the documentation since ./GetRegion.py has had the network bit separated from the map preparation bit which is now in ./PrepRegion.py.

The only gating factor on releasing 1.0 right now is Anvil.  Once Minecraft (and pymclevel, and c10t) can support 256-height worlds, I will polish up the release and get it out the door!

I hope you enjoy using the software, once the USGS servers come back up!!

Jack.

**Comment by pm2845** [comment] 2012-02-25 03:53
I managed to get the data from the USGS servers, but I ran into another
problem! (Sorry!)

Retrieving new dataset NewYorkCity...
Checking inventory service for coverage.
Inventory service has the following product IDs: L01,ND9
Configured the following layer IDs: L0102HT,ND902HT
Requested URLs for layer ID L0102HT...
Requested URLs for layer ID ND902HT...
Received download URLs, downloading now!
  Requesting download.
  request ID is 20120224.192641683.075158140096
  status is Data Request Created, Waiting for Extractor
  status is Extracting Data
  status is Extracting Data
  status is Extracting Data
  status is Extracting Metadata
  status is Extracting Metadata
  status is Retrieving Remote Archive File
  downloading 77611571.tgz now!
  Requesting download.
  request ID is 20120224.192854088.075158140096
  status is Data Request Created, Waiting for Extractor
  status is
  status is Retrieving Remote Archive File
  downloading 11212276.tgz now!
sh: gdalbuildvrt: not found
sh: gdalbuildvrt: not found
Traceback (most recent call last):
  File "GetDataset.py", line 504, in <module>
    sys.exit(main(sys.argv))
  File "GetDataset.py", line 501, in main
    warpElevation(datasetDir)
  File "GetDataset.py", line 425, in warpElevation
    os.rename(elevationimage, elevationimageorig)
OSError: [Errno 2] No such file or directory

I did a little poking around myself, it seems that the getDataset.py script
thinks that the elevation image is
"Datasets/NewYorkCity/ND902HT/ND902HT.tif", but that it really is
Datasets/NewYorkCity/ND902HT/<archive#>/<archive#>.tif.

After that though, I got to this problem in BuildArrays.py (with no extra
options):
Import error loading precompiled _nbt extension. Trying pyximport...
/home/pm/.pyxbld/temp.linux-x86_64-2.7/pyrex/pymclevel/_nbt.c: In function
__pyx_pf_9pymclevel_4_nbt_12TAG_Compound_2saveGzipped:
/home/pm/.pyxbld/temp.linux-x86_64-2.7/pyrex/pymclevel/_nbt.c:6169:13:
warning: variable __pyx_v_compresslevel set but not used
[-Wunused-but-set-variable]
/home/pm/.pyxbld/temp.linux-x86_64-2.7/pyrex/pymclevel/_nbt.c: In function
__pyx_f_9pymclevel_4_nbt_load_list:
/home/pm/.pyxbld/temp.linux-x86_64-2.7/pyrex/pymclevel/_nbt.c:8470:7:
warning: variable __pyx_v_i set but not used [-Wunused-but-set-variable]
/home/pm/.pyxbld/temp.linux-x86_64-2.7/pyrex/pymclevel/_nbt.c: At top level:
/usr/include/python2.7/cStringIO.h:62:4: warning: PycStringIO defined but
not used [-Wunused-variable]
/usr/lib/pymodules/python2.7/numpy/core/include/numpy/__multiarray_api.h:1187:1:
warning: _import_array defined but not used [-Wunused-function]
/usr/lib/pymodules/python2.7/numpy/core/include/numpy/__ufunc_api.h:196:1:
warning: _import_umath defined but not used [-Wunused-function]
Accelerated NBT module loaded via pyximport.
Processing region NewYorkCity of size (314, 376) with 4 processes...
OMG elevval -42525077188663749170569420617577136128 is less than zero
Traceback (most recent call last):
  File "BuildArrays.py", line 156, in <module>
    sys.exit(main(sys.argv))
  File "BuildArrays.py", line 128, in main
    peaks = processTiles(args, minTileRows, maxTileRows, minTileCols,
maxTileCols, processes)
  File "/home/pm/.minecraft/tools/TopoMC/tile.py", line 167, in processTiles
    peaks = [x for x in results]
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 622, in next
    raise value
OverflowError: Python int too large to convert to C long

On Wed, Feb 22, 2012 at 8:37 PM, Jack Twilley <
reply@reply.github.com

**Comment by mathuin** [comment] 2012-02-25 17:22
You need a more recent version of GDAL, I think.

gdalbuildvrt on my system is from GDAL 1.7.3 released 2010/11/10.  Check your version of gdal-bin and make sure it's up to date.  That will address the missing command issue as well as that huge-negative-value issue.

I'm pretty sure that will help fix your problems.  Also, give the other branch a try!  feature/regions is the branch name.  I will be moving it into develop sometime next week since all the primary development is complete and I am working on bug fixes, but for now it's reachable via 'git checkout feature/regions'.

Using that code I was able to build a new showcase version of New York City.

``` bash
./GetRegion.py --name NewYorkCity --ymax 40.8846 --ymin 40.6763 --xmin -74.069 --xmax -73.890
./PrepRegion.py --name NewYorkCity
./BuildRegion.py --name NewYorkCity
```

Jack.

**Comment by mathuin** [comment] 2012-02-29 16:51
I have merged the regions feature into develop, so I am closing this issue.

If you find that the new code does not work on Windows, please reopen the issue and I will work with you on identifying the root cause and resolving it.  It's almost definitely filename related, and I'm hoping we can find a quick solution if it's still broken.

Thank you again for submitting the issue, and I hope the new code works well for you!

Jack.

**Closed as completed by mathuin** 2012-02-29 16:51 UTC
